name: Blaster's Music
favicon: null
layout_spectrum: 0.91706
typography_spectrum: 0.9809951649513096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9beed'
    - '#294374'
    - '#5178b1'
    - '#050000'
  brandStrength: 0.24202916375361383
  lightness: 0.8842340547125787
  saturation: 0.7617440049070865
  rhythmicContrast: 0.75
purpose: []
