name: Blaster's Music
favicon: null
layout_spectrum: 0.19262
typography_spectrum: 0.86005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9beed'
    - '#294374'
    - '#5178b1'
    - '#050000'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
