purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3744681
  brandStrength: 0.7914894
  lightness: 0.1875
  brandColors:
    - '#010101'
    - '#FFFFFF'
    - '#00FFF9'
    - '#FF0101'
    - '#7A7A7A'
  rhythmicContrast: 0.7787234
cta:
  bucket: null
  version: null
  domain: null
name: Blaster's Music
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5276596
layout_spectrum: 1
